services:
  chatbot:
   build: ./chatbot
   ports:
    - "8000:8000"
   env_file:
    - ./chatbot/.env
  chatbot-front:
   build: ./chatbot-front
   ports:
    - "5713:5713"
   depends_on:
    - chatbot